---
- name: Install tigervnc things
  hosts: all

  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: ../vars/main.yml

    - name: install epel
      dnf:
        name:
          - epel-release
        state: latest

    - name: stop that damn firewall
      service:
        name: firewalld
        state: stopped
        enabled: no
          
    - name: install workstation dependancies
      dnf:
        name: '@workstation'
        state: present

    - name: install tigervnc
      dnf:
        name:
          - tigervnc-server
        state: latest

    - name: put the default service file is the correct place
      template:
        src: ../templates/vncserver.service.j2
        dest: /etc/systemd/system/vncserver@.service
        owner: root
        group: root
        mode: '0644'

    - name: run the daemon reload
      shell: systemctl daemon-reload

    - name: allow port 5801 into the machine
      iptables:
        chain: INPUT
        protocol: tcp
        ctstate: NEW
        destination_port: 5801
        jump: ACCEPT

    - name: allow port 5901 into the machine
      iptables:
        chain: INPUT
        protocol: tcp
        ctstate: NEW
        destination_port: 5901
        jump: ACCEPT

    - name: allow port 6001 into the machine
      iptables:
        chain: INPUT
        protocol: tcp
        ctstate: NEW
        destination_port: 6001
        jump: ACCEPT

    - name: pull down crc to the machine
      unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
        dest: /home/{{ user }}/
        remote_src: yes
